# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edde330ce1807f1690d79fc6fea585c5415fe55925c947fc6ce3f00c77c1ea625e60e0b4c2c6b8487b9478a4c4eaab1ec817820c8ad0b279d7f5841a417fdff1

test:
  secret_key_base: 905db4432ee0aa38560cf435834912237dbc9244b3c1a0c7201a2d5384749871449f152671533f3f70db068245dd08918aeae376ec28c9f1678235e63ab56c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
